// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OnThisDay.Api.Infrastructure.Data;

#nullable disable

namespace OnThisDay.Api.Migrations
{
    [DbContext(typeof(OnThisDayDbContext))]
    partial class OnThisDayDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OnThisDay.Api.Domain.Entities.Competition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text")
                        .HasColumnName("logo_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("ShortName")
                        .HasColumnType("text")
                        .HasColumnName("short_name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<int>("SportId")
                        .HasColumnType("integer")
                        .HasColumnName("sport_id");

                    b.HasKey("Id")
                        .HasName("p_k_competitions");

                    b.HasIndex("SportId")
                        .HasDatabaseName("i_x_competitions_sport_id");

                    b.ToTable("competitions");
                });

            modelBuilder.Entity("OnThisDay.Api.Domain.Entities.EventParticipant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<string>("PerformanceNote")
                        .HasColumnType("text")
                        .HasColumnName("performance_note");

                    b.Property<int?>("PersonId")
                        .HasColumnType("integer")
                        .HasColumnName("person_id");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<int>("SportEventId")
                        .HasColumnType("integer")
                        .HasColumnName("sport_event_id");

                    b.Property<int?>("TeamId")
                        .HasColumnType("integer")
                        .HasColumnName("team_id");

                    b.HasKey("Id")
                        .HasName("p_k_event_participants");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("i_x_event_participants_person_id");

                    b.HasIndex("SportEventId")
                        .HasDatabaseName("i_x_event_participants_sport_event_id");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("i_x_event_participants_team_id");

                    b.ToTable("event_participants");
                });

            modelBuilder.Entity("OnThisDay.Api.Domain.Entities.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .HasColumnType("text")
                        .HasColumnName("country");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("p_k_location");

                    b.ToTable("location");
                });

            modelBuilder.Entity("OnThisDay.Api.Domain.Entities.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Biography")
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("biography");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("birth_date");

                    b.Property<DateTime?>("DeathDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("death_date");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("firstname");

                    b.Property<int>("Gender")
                        .HasColumnType("integer")
                        .HasColumnName("gender");

                    b.Property<string>("Lastname")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("lastname");

                    b.Property<string>("Nationality")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nationality");

                    b.Property<string>("ProfileImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("profile_image_url");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("slug");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("p_k_persons");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("persons");
                });

            modelBuilder.Entity("OnThisDay.Api.Domain.Entities.Sport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("IconUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("icon_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("slug");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("p_k_sports");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("sports");
                });

            modelBuilder.Entity("OnThisDay.Api.Domain.Entities.SportEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CompetitionId")
                        .HasColumnType("integer")
                        .HasColumnName("competition_id");

                    b.Property<int>("Day")
                        .HasColumnType("integer")
                        .HasColumnName("day");

                    b.Property<string>("FullDescription")
                        .HasColumnType("text")
                        .HasColumnName("full_description");

                    b.Property<string>("Headline")
                        .HasColumnType("text")
                        .HasColumnName("headline");

                    b.Property<int?>("LocationId")
                        .HasColumnType("integer")
                        .HasColumnName("location_id");

                    b.Property<string>("MediaUrl")
                        .HasColumnType("text")
                        .HasColumnName("media_url");

                    b.Property<int>("Month")
                        .HasColumnType("integer")
                        .HasColumnName("month");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<int>("SportId")
                        .HasColumnType("integer")
                        .HasColumnName("sport_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("p_k_sport_events");

                    b.HasIndex("CompetitionId")
                        .HasDatabaseName("i_x_sport_events_competition_id");

                    b.HasIndex("LocationId")
                        .HasDatabaseName("i_x_sport_events_location_id");

                    b.HasIndex("SportId")
                        .HasDatabaseName("i_x_sport_events_sport_id");

                    b.ToTable("sport_events");
                });

            modelBuilder.Entity("OnThisDay.Api.Domain.Entities.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime>("FoundedYear")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("founded_year");

                    b.Property<string>("IconUrl")
                        .HasColumnType("text")
                        .HasColumnName("icon_url");

                    b.Property<int?>("LocationId")
                        .HasColumnType("integer")
                        .HasColumnName("location_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<int?>("SportId")
                        .HasColumnType("integer")
                        .HasColumnName("sport_id");

                    b.Property<string>("WebsiteUrl")
                        .HasColumnType("text")
                        .HasColumnName("website_url");

                    b.HasKey("Id")
                        .HasName("p_k_teams");

                    b.HasIndex("LocationId")
                        .HasDatabaseName("i_x_teams_location_id");

                    b.HasIndex("SportId")
                        .HasDatabaseName("i_x_teams_sport_id");

                    b.ToTable("teams");
                });

            modelBuilder.Entity("OnThisDay.Api.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("text")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("text")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserName")
                        .HasColumnType("text")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("p_k_users");

                    b.ToTable("users");
                });

            modelBuilder.Entity("PersonSport", b =>
                {
                    b.Property<int>("AthletesId")
                        .HasColumnType("integer")
                        .HasColumnName("athletes_id");

                    b.Property<int>("SportsId")
                        .HasColumnType("integer")
                        .HasColumnName("sports_id");

                    b.HasKey("AthletesId", "SportsId")
                        .HasName("p_k_person_sport");

                    b.HasIndex("SportsId")
                        .HasDatabaseName("i_x_person_sport_sports_id");

                    b.ToTable("person_sport");
                });

            modelBuilder.Entity("PersonTeam", b =>
                {
                    b.Property<int>("MembersId")
                        .HasColumnType("integer")
                        .HasColumnName("members_id");

                    b.Property<int>("TeamsId")
                        .HasColumnType("integer")
                        .HasColumnName("teams_id");

                    b.HasKey("MembersId", "TeamsId")
                        .HasName("p_k_person_team");

                    b.HasIndex("TeamsId")
                        .HasDatabaseName("i_x_person_team_teams_id");

                    b.ToTable("person_team");
                });

            modelBuilder.Entity("OnThisDay.Api.Domain.Entities.Competition", b =>
                {
                    b.HasOne("OnThisDay.Api.Domain.Entities.Sport", "Sport")
                        .WithMany("Competitions")
                        .HasForeignKey("SportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_competitions__sports_sport_id");

                    b.Navigation("Sport");
                });

            modelBuilder.Entity("OnThisDay.Api.Domain.Entities.EventParticipant", b =>
                {
                    b.HasOne("OnThisDay.Api.Domain.Entities.Person", "Person")
                        .WithMany("EventParticipations")
                        .HasForeignKey("PersonId")
                        .HasConstraintName("f_k_event_participants__persons_person_id");

                    b.HasOne("OnThisDay.Api.Domain.Entities.SportEvent", "SportEvent")
                        .WithMany("Participants")
                        .HasForeignKey("SportEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_event_participants__sport_events_sport_event_id");

                    b.HasOne("OnThisDay.Api.Domain.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .HasConstraintName("f_k_event_participants__teams_team_id");

                    b.Navigation("Person");

                    b.Navigation("SportEvent");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("OnThisDay.Api.Domain.Entities.SportEvent", b =>
                {
                    b.HasOne("OnThisDay.Api.Domain.Entities.Competition", "Competition")
                        .WithMany("Events")
                        .HasForeignKey("CompetitionId")
                        .HasConstraintName("f_k_sport_events_competitions_competition_id");

                    b.HasOne("OnThisDay.Api.Domain.Entities.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .HasConstraintName("f_k_sport_events_location_location_id");

                    b.HasOne("OnThisDay.Api.Domain.Entities.Sport", "Sport")
                        .WithMany("Events")
                        .HasForeignKey("SportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_sport_events_sports_sport_id");

                    b.Navigation("Competition");

                    b.Navigation("Location");

                    b.Navigation("Sport");
                });

            modelBuilder.Entity("OnThisDay.Api.Domain.Entities.Team", b =>
                {
                    b.HasOne("OnThisDay.Api.Domain.Entities.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .HasConstraintName("f_k_teams_location_location_id");

                    b.HasOne("OnThisDay.Api.Domain.Entities.Sport", "Sport")
                        .WithMany()
                        .HasForeignKey("SportId")
                        .HasConstraintName("f_k_teams_sports_sport_id");

                    b.Navigation("Location");

                    b.Navigation("Sport");
                });

            modelBuilder.Entity("PersonSport", b =>
                {
                    b.HasOne("OnThisDay.Api.Domain.Entities.Person", null)
                        .WithMany()
                        .HasForeignKey("AthletesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_person_sport_persons_athletes_id");

                    b.HasOne("OnThisDay.Api.Domain.Entities.Sport", null)
                        .WithMany()
                        .HasForeignKey("SportsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_person_sport_sports_sports_id");
                });

            modelBuilder.Entity("PersonTeam", b =>
                {
                    b.HasOne("OnThisDay.Api.Domain.Entities.Person", null)
                        .WithMany()
                        .HasForeignKey("MembersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_person_team_persons_members_id");

                    b.HasOne("OnThisDay.Api.Domain.Entities.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_person_team_teams_teams_id");
                });

            modelBuilder.Entity("OnThisDay.Api.Domain.Entities.Competition", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("OnThisDay.Api.Domain.Entities.Person", b =>
                {
                    b.Navigation("EventParticipations");
                });

            modelBuilder.Entity("OnThisDay.Api.Domain.Entities.Sport", b =>
                {
                    b.Navigation("Competitions");

                    b.Navigation("Events");
                });

            modelBuilder.Entity("OnThisDay.Api.Domain.Entities.SportEvent", b =>
                {
                    b.Navigation("Participants");
                });
#pragma warning restore 612, 618
        }
    }
}
