import React from 'react'
export const metadata = {
  title: "onthisday - شرایط استفاده",
  description: "Generated by create next app",
};
export default function terms() {
  return (
    <div className="max-w-5xl mx-auto px-8 py-20">
      <h1 className="mb-16 text-5xl font-black mb-4">
        شرایط استفاده
      </h1>
      <p className="text-lg text-gray-600 max-w-2xl">
        این سایت یک پروژه آزاد و متن باز است که هدف آن ارائه اطلاعات تاریخی و هنری است.
      </p>
      <p className="text-lg text-gray-600 max-w-2xl mt-8">
        این سایت توسط تیمی از توسعه‌دهندگان و دانشجویان متخصص در زمینه‌های مختلف ایجاد شده است. هدف اصلی این سایت ارائه اطلاعات تاریخی و هنری به یک شکل ساده و قابل دسترسی است.
      </p>
    </div>
  )
}
